export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const GET_USER_SUCCESS = "GET_NOTIFY_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";