export const GET_ROOMS_SUCCESS = "GET_FRIEND_LIST_SUCCESS";
export const GET_JOINED_ROOM_SUCCESS = "GET_JOINED_ROOM_SUCCESS"
export const GET_CREATED_ROOM_SUCCESS = "GET_CREATED_ROOM_SUCCESS"
export const FORM_RESET = "FORM_RESET";
export const SHOW_LOADER = "SHOW_LOADER";

export const REGISTER_BOOKING_ROOM_SUCCESS = 'REGISTER_BOOKING_ROOM_SUCCESS';
export const REGISTER_BOOKING_ROOM_FAILURE = 'REGISTER_BOOKING_ROOM_FAILURE';