export const CREATE_NEW_FEEDBACK_SUCCESS = "CREATE_NEW_FEEDBACK_SUCCESS";
export const CREATE_NEW_FEEDBACK_FAILURE = "CREATE_NEW_FEEDBACK_FAILURE";
export const GET_FEEDBACK_TYPE_SUCCESS = "GET_FEEDBACK_TYPE_SUCCESS";