export const SHOW_LOADER = 'SHOW_LOADER';
export const FORM_RESET = 'FORM_RESET';
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';
export const GET_FRIENDS_EVEN_REQUEST_SUCCESS = 'GET_FRIENDS_EVEN_REQUEST_SUCCESS';

export const ADD_FRIENDS_SUCCESS = 'ADD_FRIENDS_SUCCESS';
export const ADD_FRIENDS_FAILURE = 'ADD_FRIENDS_FAILURE';

export const GET_FRIENDS_BY_TASK_SUCCESS = 'GET_FRIENDS_BY_TASK_SUCCESS';
export const GET_FRIENDS_BY_TASK_FAILURE = 'GET_FRIENDS_BY_TASK_FAILURE';

export const GET_FRIENDS_RECENT = 'GET_FRIENDS_RECENT';

export const ACCEPT_FRIEND_REQUEST_SUCCESS = 'ACCEPT_FRIEND_REQUEST_SUCCESS';
export const ACCEPT_FRIEND_REQUEST_FAILURE = 'ACCEPT_FRIEND_REQUEST_FAILURE';

export const DENY_FRIEND_REQUEST_SUCCESS = 'DENY_FRIEND_REQUEST_SUCCESS';
export const DENY_FRIEND_REQUEST_FAILURE = 'DENY_FRIEND_REQUEST_FAILURE';

export const SEARCH_FRIENDS_SUCCESS = 'SEARCH_FRIENDS_SUCCESS';
export const SEARCH_FRIENDS_FAILURE = 'SEARCH_FRIENDS_FAILURE';

export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS';
export const DELETE_FRIEND_FAILURE = 'DELETE_FRIEND_FAILURE';