export const GET_INFORMATION_JOIN_SUCCESS = "GET_INFORMATION_JOIN_SUCCESS";
export const GET_INFORMATION_JOIN_FAILURE = "GET_INFORMATION_JOIN_FAILURE";

export const GET_ROOM_INFORMATION_SUCCESS = "GET_ROOM_INFORMATION_SUCCESS";
export const GET_ROOM_INFORMATION_FAILURE = "GET_ROOM_INFORMATION_FAILURE";

export const UPDATE_LOCK_ROOM_SUCCESS = "UPDATE_LOCK_ROOM_SUCCESS";
export const UPDATE_LOCK_ROOM_FAILURE = "UPDATE_LOCK_ROOM_FAILURE";

export const GET_LIST_FRIEND_SUCCESS = "GET_LIST_FRIEND_SUCCESS";
export const GET_LIST_FRIEND_FAILURE = "GET_LIST_FRIEND_FAILURE";

export const SEND_INVITE_TO_ALL_SUCCESS = "SEND_INVITE_TO_ALL_SUCCESS";
export const SEND_INVITE_TO_ALL_FAILURE = "SEND_INVITE_TO_ALL_FAILURE";

export const GET_LIST_TASK_TO_CHOOSE_SUCCESS = "GET_LIST_TASK_TO_CHOOSE_SUCCESS";
export const GET_LIST_TASK_TO_CHOOSE_FAILURE = "GET_LIST_TASK_TO_CHOOSE_FAILURE";

export const GET_TASK_CHOOSE_BY_ID_SUCCESS = "GET_TASK_CHOOSE_BY_ID_SUCCESS";
export const GET_TASK_CHOOSE_BY_ID_FAILURE = "GET_TASK_CHOOSE_BY_ID_FAILURE";

export const ADD_TASK_CHOOSE_FOR_USER_SUCCESS = "ADD_TASK_CHOOSE_FOR_USER_SUCCESS";
export const ADD_TASK_CHOOSE_FOR_USER_FAILURE = "ADD_TASK_CHOOSE_FOR_USER_FAILURE";

export const COMPLETE_TASK_SUCCESS = "COMPLETE_TASK_SUCCESS";
export const COMPLETE_TASK_FAILURE = "COMPLETE_TASK_FAILURE";

export const CANCEL_TASK_SUCCESS = "CANCEL_TASK_SUCCESS";
export const CANCEL_TASK_FAILURE = "CANCEL_TASK_FAILURE";

export const ACCEPT_ROOM_TASK_SUCCESS = "ACCEPT_ROOM_TASK_SUCCESS";
export const ACCEPT_ROOM_TASK_FAILURE = "ACCEPT_ROOM_TASK_FAILURE";

export const OUT_MEET_SUCCESS = 'OUT_MEET_SUCCESS';
export const OUT_MEET_FAILURE = 'OUT_MEET_FAILURE';

export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const GET_MEMBERS_FAILURE = 'GET_MEMBERS_FAILURE';

export const RESET_USER_ROOM_TASK_SUCCESS = 'RESET_USER_ROOM_TASK_SUCCESS';
export const RESET_USER_ROOM_TASK_FAILURE = 'RESET_USER_ROOM_TASK_FAILURE';