export const GET_LIST_NOTIFICATION_SUCCESS = "GET_LIST_NOTIFICATION_SUCCESS";
export const GET_LIST_NOTIFICATION_FAILURE = "GET_LIST_NOTIFICATION_FAILURE";

export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAILURE = "DELETE_NOTIFICATION_FAILURE";

export const SEND_INVITE_SUCCESS = "SEND_INVITE_SUCCESS";
export const SEND_INVITE_FAILURE = "SEND_INVITE_FAILURE";