export const CREATE_NEW_ROOM_SUCCESS = "CREATE_NEW_ROOM_SUCCESS";
export const CREATE_NEW_ROOM_FAILURE = "CREATE_NEW_ROOM_FAILURE";

export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";
export const GET_JOINED_ROOM_SUCCESS = "GET_JOINED_ROOM_SUCCESS"
export const GET_CREATED_ROOM_SUCCESS = "GET_CREATED_ROOM_SUCCESS"

export const DELETE_MY_ROOM_SUCCESS = 'DELETE_MY_ROOM_SUCCESS';
export const DELETE_MY_ROOM_FAILURE = 'DELETE_MY_ROOM_FAILURE';

export const SHOW_LOADER = "SHOW_LOADER";