export const SHOW_LOADER = "SHOW_LOADER";
export const FORM_RESET = "FORM_RESET";
export const GET_COMMUNITY_SUCCESS = "GET_USER_SUCCESS";
export const GET_PERSONAL_SUCCESS = "GET_PERSONAL_SUCCESS";
export const GET_RANK_INFO_SUCCESS = "GET_RANK_INFO_SUCCESS";
