export const GET_TIME_CHECK_ADD_RECOMMEND_TASK_SUCCESS = "GET_TIME_CHECK_ADD_RECOMMEND_TASK_SUCCESS";
export const GET_TIME_CHECK_ADD_RECOMMEND_TASK_FAILURE = "GET_TIME_CHECK_ADD_RECOMMEND_TASK_FAILURE";

export const GET_TASKS_PROPOSED_SUCCESS = "GET_TASKS_PROPOSED_SUCCESS";
export const GET_TASKS_PROPOSED_FAILURE = "GET_TASKS_PROPOSED_FAILURE";

export const ADD_TASK_PROPOSED_SUCCESS = "ADD_TASK_PROPOSED_SUCCESS";
export const ADD_TASK_PROPOSED_FAILURE = "ADD_TASK_PROPOSED_FAILURE";