export const GET_TASK_BY_ID_SUCCESS = "GET_TASK_BY_ID_SUCCESS";
export const GET_TASK_BY_ID_FAILURE = "GET_TASK_BY_ID_FAILURE";

// TASK GROUP
export const GET_LIST_TASK_NOT_START_GROUP_SUCCESS = "GET_LIST_TASK_NOT_START_GROUP_SUCCESS";
export const GET_LIST_TASK_NOT_START_GROUP_FAILURE = "GET_LIST_TASK_NOT_START_GROUP_FAILURE";

export const GET_LIST_TASK_DOING_GROUP_SUCCESS = "GET_LIST_TASK_DOING_GROUP_SUCCESS";
export const GET_LIST_TASK_DOING_GROUP_FAILURE = "GET_LIST_TASK_DOING_GROUP_FAILURE";

export const GET_LIST_TASK_DONE_GROUP_SUCCESS = "GET_LIST_TASK_DONE_GROUP_SUCCESS";
export const GET_LIST_TASK_DONE_GROUP_FAILURE = "GET_LIST_TASK_DONE_GROUP_FAILURE";

export const GET_LIST_TASK_FAVORITE_GROUP_SUCCESS = "GET_LIST_TASK_FAVORITE_GROUP_SUCCESS";
export const GET_LIST_TASK_FAVORITE_GROUP_FAILURE = "GET_LIST_TASK_FAVORITE_GROUP_FAILURE";

// TASK PERSONAL
export const GET_LIST_TASK_DOING_PERSONAL_SUCCESS = "GET_LIST_TASK_DOING_PERSONAL_SUCCESS";
export const GET_LIST_TASK_DOING_PERSONAL_FAILURE = "GET_LIST_TASK_DOING_PERSONAL_FAILURE";

export const GET_LIST_TASK_DONE_PERSONAL_SUCCESS = "GET_LIST_TASK_DONE_PERSONAL_SUCCESS";
export const GET_LIST_TASK_DONE_PERSONAL_FAILURE = "GET_LIST_TASK_DONE_PERSONAL_FAILURE";

export const UPDATE_TASK_PERSONAL_SUCCESS = "UPDATE_TASK_PERSONAL_SUCCESS";
export const UPDATE_TASK_PERSONAL_FAILURE = "UPDATE_TASK_PERSONAL_FAILURE";


// FAVORITE

export const UPDATE_FAVORITE_FOR_TASK_SUCCESS = "UPDATE_FAVORITE_FOR_TASK_SUCCESS";
export const UPDATE_FAVORITE_FOR_TASK_FAILURE = "UPDATE_FAVORITE_FOR_TASK_FAILURE";