export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAILURE = 'GET_ACCOUNTS_FAILURE';
export const UPDATE_ACCOUNTS_SUCCESS = 'UPDATE_ACCOUNTS_SUCCESS';
export const UPDATE_ACCOUNTS_FAILURE = 'UPDATE_ACCOUNTS_FAILURE';
export const DELETE_ACCOUNTS_SUCCESS = 'DELETE_ACCOUNTS_SUCCESS';
export const DELETE_ACCOUNTS_FAILURE = 'DELETE_ACCOUNTS_FAILURE';
export const ADD_ACCOUNTS_SUCCESS = 'ADD_ACCOUNTS_SUCCESS';
export const ADD_ACCOUNTS_FAILURE = 'ADD_ACCOUNTS_FAILURE';
