export const GET_LIST_FEEDBACK_SUCCESS = 'GET_LIST_FEEDBACK_SUCCESS';
export const GET_LIST_FEEDBACK_FAILURE = 'GET_LIST_FEEDBACK_FAILURE';
export const DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS';
export const DELETE_FEEDBACK_FAILURE = 'DELETE_FEEDBACK_FAILURE';
export const CONFIRM_FEEDBACK_SUCCESS = 'CONFIRM_FEEDBACK_SUCCESS';
export const CONFIRM_FEEDBACK_FAILURE = 'CONFIRM_FEEDBACK_FAILURE';
