export const GET_LIST_ROOM_SUCCESS = 'GET_LIST_ROOM_SUCCESS';
export const GET_LIST_ROOM_FAILURE = 'GET_LIST_ROOM_FAILURE';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAILURE = 'DELETE_ROOM_FAILURE';
