export const GET_SOFTSKILLS_SUCCESS = 'GET_SOFTSKILLS_SUCCESS';
export const GET_SOFTSKILLS_FAILURE = 'GET_SOFTSKILLS_FAILURE';
export const ADD_SOFTSKILLS_SUCCESS = 'ADD_SOFTSKILLS_SUCCESS';
export const ADD_SOFTSKILLS_FAILURE = 'ADD_SOFTSKILLS_FAILURE';
export const UPDATE_SOFTSKILLS_SUCCESS = 'UPDATE_SOFTSKILLS_SUCCESS';
export const UPDATE_SOFTSKILLS_FAILURE = 'UPDATE_SOFTSKILLS_FAILURE';
export const DELETE_SOFTSKILLS_SUCCESS = 'DELETE_SOFTSKILLS_SUCCESS';
export const DELETE_SOFTSKILLS_FAILURE = 'DELETE_SOFTSKILLS_FAILURE';
