export const SHOW_LOADER = 'SHOW_LOADER';
export const FORM_RESET = 'FORM_RESET';
export const GET_NUMBER_USER_SUCCESS = 'GET_NUMBER_USER_SUCCESS';
export const GET_TOTAL_ROOMS_SUCCESS = 'GET_PERGET_TOTAL_ROOMS_SUCCESSSONAL_SUCCESS';
export const GET_RANK_INFO_SUCCESS = 'GET_RANK_INFO_SUCCESS';
export const GET_NUMBER_JOIN_SUCCESS = 'GET_NUMBER_JOIN_SUCCESS';
export const GET_NUMBER_ROOM_SUCCESS = 'GET_NUMBER_ROOM_SUCCESS';
export const GET_SOFTSKILL_SUCCESS = 'GET_SOFTSKILL_SUCCESS';
