export const GET_GROUP_TASKS_SUCCESS = 'GET_GROUP_TASKS_SUCCESS';
export const GET_GROUP_TASKS_FAILURE = 'GET_GROUP_TASKS_FAILURE';
export const ADD_GROUP_TASKS_SUCCESS = 'ADD_GROUP_TASKS_SUCCESS';
export const ADD_GROUP_TASKS_FAILURE = 'ADD_GROUP_TASKS_FAILURE';
export const UPDATE_GROUP_TASKS_SUCCESS = 'UPDATE_GROUP_TASKS_SUCCESS';
export const UPDATE_GROUP_TASKS_FAILURE = 'UPDATE_GROUP_TASKS_FAILURE';
export const DELETE_GROUP_TASKS_SUCCESS = 'DELETE_GROUP_TASKS_SUCCESS';
export const DELETE_GROUP_TASKS_FAILURE = 'DELETE_GROUP_TASKS_FAILURE';
