export const GET_INDIVIDUAL_TASKS_SUCCESS = 'GET_INDIVIDUAL_TASKS_SUCCESS';
export const GET_INDIVIDUAL_TASKS_FAILURE = 'GET_INDIVIDUAL_TASKS_FAILURE';
export const ADD_INDIVIDUAL_TASKS_SUCCESS = 'ADD_INDIVIDUAL_TASKS_SUCCESS';
export const ADD_INDIVIDUAL_TASKS_FAILURE = 'ADD_INDIVIDUAL_TASKS_FAILURE';
export const UPDATE_INDIVIDUAL_TASKS_SUCCESS = 'UPDATE_INDIVIDUAL_TASKS_SUCCESS';
export const UPDATE_INDIVIDUAL_TASKS_FAILURE = 'UPDATE_INDIVIDUAL_TASKS_FAILURE';
export const DELETE_INDIVIDUAL_TASKS_SUCCESS = 'DELETE_INDIVIDUAL_TASKS_SUCCESS';
export const DELETE_INDIVIDUAL_TASKS_FAILURE = 'DELETE_INDIVIDUAL_TASKS_FAILURE';
