export const GET_RECOMMEND_TASKS_SUCCESS = 'GET_RECOMMEND_TASKS_SUCCESS';
export const GET_RECOMMEND_TASKS_FAILURE = 'GET_RECOMMEND_TASKS_FAILURE';
export const UPDATE_RECOMMEND_TASKS_SUCCESS = 'UPDATE_RECOMMEND_TASKS_SUCCESS';
export const UPDATE_RECOMMEND_TASKS_FAILURE = 'UPDATE_RECOMMEND_TASKS_FAILURE';
export const DELETE_RECOMMEND_TASKS_SUCCESS = 'DELETE_RECOMMEND_TASKS_SUCCESS';
export const DELETE_RECOMMEND_TASKS_FAILURE = 'DELETE_RECOMMEND_TASKS_FAILURE';
